---
k3s_version: v1.17.5+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
http_proxy: ""
https_proxy: ""
no_proxy: "localhost,127.0.0.1,*.local,10.42.0.0/16"
